name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser'
        required: false
        default: 'chromium'
        type: choice
        options:
        - chromium
        - firefox
        - webkit
        - all
      spec:
        description: 'Path to the spec file'
        required: false
        default: './tests/*.ts'
        type: string
      smoke:
        description: 'Run smoke tests only'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Get installed playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(npx playwright --version)" >> $GITHUB_ENV
      - name: Playwright cache
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-playwright-
            ${{ runner.os }}-
      - name: Cache modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - name: Install missing dependencies for WebKit
        run: |
          sudo apt-get update
          sudo apt-get install -y libwoff1 libwoff-dev
      - name: Create .env file
        run: mkdir -p env && echo "${{ secrets.ENV }}" > env/.env
      - name: Run Playwright tests smoke
        if: ${{ github.event.inputs.smoke == 'true' && github.event.inputs.browser != 'all' }}
        run: |
          echo "Running smoke tests"
          npx playwright test ${{ github.event.inputs.spec }} --project ${{ github.event.inputs.browser }} --grep @smoke 
      - name: Run Playwright tests smoke all
        if: ${{ github.event.inputs.smoke == 'true' && github.event.inputs.browser == 'all' }}
        run: |
          echo "Running smoke tests all"
          npx playwright test ${{ github.event.inputs.spec }} --grep @smoke
      - name: Run Playwright tests
        if: ${{ github.event.inputs.smoke != 'true' && github.event.inputs.browser != 'all' }}
        run: |
          echo "Running all tests"
          npx playwright test ${{ github.event.inputs.spec }} --project ${{ github.event.inputs.browser }}
      - name: Run Playwright tests in all browsers
        if: ${{ github.event.inputs.smoke != 'true' && github.event.inputs.browser == 'all' }}
        run: npx playwright test ${{ github.event.inputs.spec }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30